"""v0.16.6 migration

Revision ID: 215d794b3041
Revises: da1a7a9cf8ac
Create Date: 2026-01-11 22:35:17.646195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "215d794b3041"
down_revision: Union[str, None] = "da1a7a9cf8ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Modify users_privacy_settings_user_id index to be unique
    op.drop_index(
        op.f("ix_users_privacy_settings_user_id"), table_name="users_privacy_settings"
    )
    op.create_index(
        op.f("ix_users_privacy_settings_user_id"),
        "users_privacy_settings",
        ["user_id"],
        unique=True,
    )
    # Create IdP link tokens table
    op.create_table(
        "idp_link_tokens",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="One-time link token (secrets.token_urlsafe(32))",
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID linking the identity provider",
        ),
        sa.Column(
            "idp_id",
            sa.Integer(),
            nullable=False,
            comment="Identity provider ID being linked",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Token creation timestamp",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=False,
            comment="Token expiry at 60 seconds (cleanup marker)",
        ),
        sa.Column(
            "used",
            sa.Boolean(),
            nullable=False,
            comment="Single-use flag (False - unused, True - used)",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="Client IP address (IPv6 max length)",
        ),
        sa.ForeignKeyConstraint(
            ["idp_id"], ["identity_providers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_idp_link_tokens_expires_at"),
        "idp_link_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idp_link_tokens_id"), "idp_link_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_idp_link_tokens_idp_id"), "idp_link_tokens", ["idp_id"], unique=False
    )
    op.create_index(
        op.f("ix_idp_link_tokens_user_id"), "idp_link_tokens", ["user_id"], unique=False
    )
    # Set comments on garminconnect_oauth1 and garminconnect_oauth2 columns
    op.alter_column(
        "users_integrations",
        "garminconnect_oauth1",
        existing_type=sa.JSON(),
        comment="Garmin OAuth1 token",
        existing_nullable=True,
    )
    op.alter_column(
        "users_integrations",
        "garminconnect_oauth2",
        existing_type=sa.JSON(),
        comment="Garmin OAuth2 token",
        existing_nullable=True,
    )
    # Drop and recreate users_integrations_user_id index as unique
    op.drop_index(
        op.f("ix_users_integrations_user_id"), table_name="users_integrations"
    )
    op.create_index(
        op.f("ix_users_integrations_user_id"),
        "users_integrations",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert users_integrations_user_id index to non-unique
    op.drop_index(
        op.f("ix_users_integrations_user_id"), table_name="users_integrations"
    )
    op.create_index(
        op.f("ix_users_integrations_user_id"),
        "users_integrations",
        ["user_id"],
        unique=False,
    )
    # Remove comments on garminconnect_oauth1 and garminconnect_oauth2 columns
    op.alter_column(
        "users_integrations",
        "garminconnect_oauth2",
        existing_type=sa.JSON(),
        comment=None,
        existing_comment="Garmin OAuth2 token",
        existing_nullable=True,
    )
    op.alter_column(
        "users_integrations",
        "garminconnect_oauth1",
        existing_type=sa.JSON(),
        comment=None,
        existing_comment="Garmin OAuth1 token",
        existing_nullable=True,
    )
    # Remove IdP link tokens table
    op.drop_index(op.f("ix_idp_link_tokens_user_id"), table_name="idp_link_tokens")
    op.drop_index(op.f("ix_idp_link_tokens_idp_id"), table_name="idp_link_tokens")
    op.drop_index(op.f("ix_idp_link_tokens_id"), table_name="idp_link_tokens")
    op.drop_index(op.f("ix_idp_link_tokens_expires_at"), table_name="idp_link_tokens")
    op.drop_table("idp_link_tokens")
    # Revert users_privacy_settings_user_id index to non-unique
    op.drop_index(
        op.f("ix_users_privacy_settings_user_id"), table_name="users_privacy_settings"
    )
    op.create_index(
        op.f("ix_users_privacy_settings_user_id"),
        "users_privacy_settings",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
