"""v0.16.5 migration

Revision ID: da1a7a9cf8ac
Revises: ed5f1c867943
Create Date: 2025-12-26 22:34:32.718821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da1a7a9cf8ac"
down_revision: Union[str, None] = "ed5f1c867943"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to server_settings table
    op.add_column(
        "server_settings",
        sa.Column(
            "tileserver_url",
            sa.String(),
            nullable=True,
            comment="URL template for the map tileserver",
        ),
    )
    op.add_column(
        "server_settings",
        sa.Column(
            "tileserver_attribution",
            sa.String(),
            nullable=True,
            comment="Attribution string for the map tileserver",
        ),
    )
    op.add_column(
        "server_settings",
        sa.Column(
            "map_background_color",
            sa.String(),
            nullable=True,
            comment="Background color for the map",
        ),
    )

    op.execute(
        "UPDATE server_settings SET tileserver_url = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png' WHERE tileserver_url IS NULL"
    )
    op.execute(
        "UPDATE server_settings SET tileserver_attribution = '&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors' WHERE tileserver_attribution IS NULL"
    )
    op.execute(
        "UPDATE server_settings SET map_background_color = '#dddddd' WHERE map_background_color IS NULL"
    )

    op.alter_column(
        "server_settings",
        "tileserver_url",
        nullable=False,
        comment="URL template for the map tileserver",
        existing_type=sa.String(),
    )
    op.alter_column(
        "server_settings",
        "tileserver_attribution",
        nullable=False,
        comment="Attribution string for the map tileserver",
        existing_type=sa.String(),
    )
    op.alter_column(
        "server_settings",
        "map_background_color",
        nullable=False,
        comment="Background color for the map",
        existing_type=sa.String(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the columns from server_settings table
    op.drop_column("server_settings", "map_background_color")
    op.drop_column("server_settings", "tileserver_attribution")
    op.drop_column("server_settings", "tileserver_url")
    # ### end Alembic commands ###
