"""v0.16.7 migration

Revision ID: 262ec21a6c15
Revises: 215d794b3041
Create Date: 2026-01-13 11:36:50.047064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "262ec21a6c15"
down_revision: Union[str, None] = "215d794b3041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mapping from old integer values to new string values
ACTIVITY_TYPE_MAP = {
    1: "run",
    2: "bike",
    3: "swim",
    4: "walk",
    5: "strength",
    6: "cardio",
}

GOAL_TYPE_MAP = {
    1: "calories",
    2: "activities",
    3: "distance",
    4: "elevation",
    5: "duration",
}

GENDER_MAP = {
    1: "male",
    2: "female",
    3: "unspecified",
}

ACCESS_TYPE_MAP = {
    1: "regular",
    2: "admin",
}

WEEK_DAY_MAP = {
    0: "sunday",
    1: "monday",
    2: "tuesday",
    3: "wednesday",
    4: "thursday",
    5: "friday",
    6: "saturday",
}

UNITS_MAP = {
    1: "metric",
    2: "imperial",
}

CURRENCY_MAP = {
    1: "euro",
    2: "dollar",
    3: "pound",
}
ACTIVITY_VISIBILITY_MAP = {
    0: "public",
    1: "followers",
    2: "private",
}

# Reverse mappings for downgrade
ACTIVITY_TYPE_REVERSE_MAP = {v: k for k, v in ACTIVITY_TYPE_MAP.items()}
GOAL_TYPE_REVERSE_MAP = {v: k for k, v in GOAL_TYPE_MAP.items()}
GENDER_REVERSE_MAP = {v: k for k, v in GENDER_MAP.items()}
ACCESS_TYPE_REVERSE_MAP = {v: k for k, v in ACCESS_TYPE_MAP.items()}
WEEK_DAY_REVERSE_MAP = {v: k for k, v in WEEK_DAY_MAP.items()}
UNITS_REVERSE_MAP = {v: k for k, v in UNITS_MAP.items()}
CURRENCY_REVERSE_MAP = {v: k for k, v in CURRENCY_MAP.items()}
ACTIVITY_VISIBILITY_REVERSE_MAP = {v: k for k, v in ACTIVITY_VISIBILITY_MAP.items()}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update comments in users_identity_providers table
    op.alter_column(
        "users_identity_providers",
        "idp_subject",
        existing_type=sa.String(length=500),
        comment="Subject/ID from the identity provider",
        existing_comment="Subject/ID from the identity provider (unique per IdP)",
        existing_nullable=False,
    )
    op.alter_column(
        "users_identity_providers",
        "last_login",
        existing_type=sa.DateTime(),
        comment="Last login using this IdP",
        existing_comment="Last time user logged in with this IdP",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "idp_refresh_token_updated_at",
        existing_type=sa.DateTime(),
        comment="Last refresh token update",
        existing_comment="Last refresh",
        existing_nullable=True,
    )
    # Add tileserver_api_key column to server_settings table
    op.add_column(
        "server_settings",
        sa.Column(
            "tileserver_api_key",
            sa.String(length=512),
            nullable=True,
            comment="API key encrypted for the tile server",
        ),
    )
    # Change users_goals table
    # Step 1: Add new string columns
    op.add_column(
        "users_goals",
        sa.Column(
            "activity_type_new",
            sa.String(length=50),
            nullable=True,
            comment="Activity type (e.g., 'run', 'bike', 'swim')",
        ),
    )
    op.add_column(
        "users_goals",
        sa.Column(
            "goal_type_new",
            sa.String(length=50),
            nullable=True,
            comment="Goal type (e.g., 'calories', 'distance', 'duration')",
        ),
    )

    # Step 2: Migrate data from integer to string values
    connection = op.get_bind()

    # Update activity_type_new based on old activity_type values
    for old_val, new_val in ACTIVITY_TYPE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_goals SET activity_type_new = :new_val "
                "WHERE activity_type = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Update goal_type_new based on old goal_type values
    for old_val, new_val in GOAL_TYPE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_goals SET goal_type_new = :new_val "
                "WHERE goal_type = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Step 3: Drop old integer columns
    op.drop_column("users_goals", "activity_type")
    op.drop_column("users_goals", "goal_type")

    # Step 4: Rename new columns to original names
    op.alter_column(
        "users_goals",
        "activity_type_new",
        new_column_name="activity_type",
        nullable=False,
    )
    op.alter_column(
        "users_goals",
        "goal_type_new",
        new_column_name="goal_type",
        nullable=False,
    )
    # Change users table - convert integer enums to string enums
    # Step 1: Add new string columns
    op.add_column(
        "users",
        sa.Column(
            "gender_new",
            sa.String(length=20),
            nullable=True,
            comment="User gender (male, female, unspecified)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "access_type_new",
            sa.String(length=20),
            nullable=True,
            comment="User type (regular, admin)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "first_day_of_week_new",
            sa.String(length=20),
            nullable=True,
            comment="User first day of week (sunday, monday, etc.)",
        ),
    )

    # Step 2: Migrate data from integer to string values
    connection = op.get_bind()

    # Update gender_new based on old gender values
    for old_val, new_val in GENDER_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users SET gender_new = :new_val " "WHERE gender = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Update access_type_new based on old access_type values
    for old_val, new_val in ACCESS_TYPE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users SET access_type_new = :new_val "
                "WHERE access_type = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Update first_day_of_week_new based on old first_day_of_week values
    for old_val, new_val in WEEK_DAY_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users SET first_day_of_week_new = :new_val "
                "WHERE first_day_of_week = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Step 3: Drop old integer columns
    op.drop_column("users", "gender")
    op.drop_column("users", "access_type")
    op.drop_column("users", "first_day_of_week")

    # Step 4: Rename new columns to original names and set not null
    op.alter_column(
        "users",
        "gender_new",
        new_column_name="gender",
        nullable=False,
    )
    op.alter_column(
        "users",
        "access_type_new",
        new_column_name="access_type",
        nullable=False,
    )
    op.alter_column(
        "users",
        "first_day_of_week_new",
        new_column_name="first_day_of_week",
        nullable=False,
    )

    # Change server_settings table - convert units and currency to string enums
    # Step 1: Add new string columns
    op.add_column(
        "server_settings",
        sa.Column(
            "units_new",
            sa.String(length=20),
            nullable=True,
            comment="Units (metric, imperial)",
        ),
    )
    op.add_column(
        "server_settings",
        sa.Column(
            "currency_new",
            sa.String(length=20),
            nullable=True,
            comment="Currency (euro, dollar, pound)",
        ),
    )

    # Step 2: Migrate data from integer to string values
    # Update units_new based on old units values
    for old_val, new_val in UNITS_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE server_settings SET units_new = :new_val "
                "WHERE units = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Update currency_new based on old currency values
    for old_val, new_val in CURRENCY_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE server_settings SET currency_new = :new_val "
                "WHERE currency = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Step 3: Drop old integer columns
    op.drop_column("server_settings", "units")
    op.drop_column("server_settings", "currency")

    # Step 4: Rename new columns to original names and set not null
    op.alter_column(
        "server_settings",
        "units_new",
        new_column_name="units",
        nullable=False,
    )
    op.alter_column(
        "server_settings",
        "currency_new",
        new_column_name="currency",
        nullable=False,
    )

    # Change users table - convert units and currency to string enums
    # Step 1: Add new string columns
    op.add_column(
        "users",
        sa.Column(
            "units_new",
            sa.String(length=20),
            nullable=True,
            comment="User units (metric, imperial)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "currency_new",
            sa.String(length=20),
            nullable=True,
            comment="User currency (euro, dollar, pound)",
        ),
    )

    # Step 2: Migrate data from integer to string values
    # Update units_new based on old units values
    for old_val, new_val in UNITS_MAP.items():
        connection.execute(
            sa.text("UPDATE users SET units_new = :new_val " "WHERE units = :old_val"),
            {"new_val": new_val, "old_val": old_val},
        )

    # Update currency_new based on old currency values
    for old_val, new_val in CURRENCY_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users SET currency_new = :new_val " "WHERE currency = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Step 3: Drop old integer columns
    op.drop_column("users", "units")
    op.drop_column("users", "currency")

    # Step 4: Rename new columns to original names and set not null
    op.alter_column(
        "users",
        "units_new",
        new_column_name="units",
        nullable=False,
    )
    op.alter_column(
        "users",
        "currency_new",
        new_column_name="currency",
        nullable=False,
    )

    # Change users_privacy_settings table - convert default_activity_visibility to string enum
    # Step 1: Add new string column
    op.add_column(
        "users_privacy_settings",
        sa.Column(
            "default_activity_visibility_new",
            sa.String(length=20),
            nullable=True,
            comment="public, followers, private",
        ),
    )

    # Step 2: Migrate data from integer to string values
    connection = op.get_bind()

    # Update default_activity_visibility_new based on old default_activity_visibility values
    for old_val, new_val in ACTIVITY_VISIBILITY_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_privacy_settings SET default_activity_visibility_new = :new_val "
                "WHERE default_activity_visibility = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Step 3: Drop old integer column
    op.drop_column("users_privacy_settings", "default_activity_visibility")

    # Step 4: Rename new column to original name and set not null
    op.alter_column(
        "users_privacy_settings",
        "default_activity_visibility_new",
        new_column_name="default_activity_visibility",
        nullable=False,
    )

    # Alter the idp_id column to be nullable
    op.alter_column(
        "oauth_states",
        "idp_id",
        existing_type=sa.Integer(),
        nullable=True,
        existing_comment="Identity provider ID",
        comment="Identity provider ID (may be null if mobile logic)",
    )

    # Delete all existing sessions because of changes on users table
    op.execute("DELETE FROM users_sessions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter the idp_id column back to be non-nullable
    op.alter_column(
        "oauth_states",
        "idp_id",
        existing_type=sa.Integer(),
        nullable=False,
        existing_comment="Identity provider ID (may be null if mobile logic)",
        comment="Identity provider ID",
    )
    # Revert changes to users_privacy_settings table
    # Step 1: Add old integer column back
    op.add_column(
        "users_privacy_settings",
        sa.Column(
            "default_activity_visibility_old",
            sa.Integer(),
            nullable=True,
            comment="0 - public, 1 - followers, 2 - private",
        ),
    )

    # Step 2: Migrate data from string back to integer values
    connection = op.get_bind()

    # Update default_activity_visibility_old based on current default_activity_visibility string values
    for str_val, int_val in ACTIVITY_VISIBILITY_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_privacy_settings SET default_activity_visibility_old = :int_val "
                "WHERE default_activity_visibility = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Step 3: Drop string column
    op.drop_column("users_privacy_settings", "default_activity_visibility")

    # Step 4: Rename old column to original name and set not null
    op.alter_column(
        "users_privacy_settings",
        "default_activity_visibility_old",
        new_column_name="default_activity_visibility",
        nullable=False,
    )

    connection = op.get_bind()

    # Revert changes to users table
    # Step 1: Add old integer columns back
    op.add_column(
        "users",
        sa.Column(
            "units_old",
            sa.Integer(),
            nullable=True,
            comment="User units (1=metric, 2=imperial)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "currency_old",
            sa.Integer(),
            nullable=True,
            comment="User currency (1=euro, 2=dollar, 3=pound)",
        ),
    )

    # Step 2: Migrate data from string back to integer values
    # Update units_old based on current units string values
    for str_val, int_val in UNITS_REVERSE_MAP.items():
        connection.execute(
            sa.text("UPDATE users SET units_old = :int_val " "WHERE units = :str_val"),
            {"int_val": int_val, "str_val": str_val},
        )

    # Update currency_old based on current currency string values
    for str_val, int_val in CURRENCY_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users SET currency_old = :int_val " "WHERE currency = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Step 3: Drop string columns
    op.drop_column("users", "units")
    op.drop_column("users", "currency")

    # Step 4: Rename old columns to original names and set not null
    op.alter_column(
        "users",
        "units_old",
        new_column_name="units",
        nullable=False,
    )
    op.alter_column(
        "users",
        "currency_old",
        new_column_name="currency",
        nullable=False,
    )

    # Revert changes to server_settings table
    # Step 1: Add old integer columns back
    op.add_column(
        "server_settings",
        sa.Column(
            "units_old",
            sa.Integer(),
            nullable=True,
            comment="Units (1=metric, 2=imperial)",
        ),
    )
    op.add_column(
        "server_settings",
        sa.Column(
            "currency_old",
            sa.Integer(),
            nullable=True,
            comment="Currency (1=euro, 2=dollar, 3=pound)",
        ),
    )

    # Step 2: Migrate data from string back to integer values
    # Update units_old based on current units string values
    for str_val, int_val in UNITS_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE server_settings SET units_old = :int_val "
                "WHERE units = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Update currency_old based on current currency string values
    for str_val, int_val in CURRENCY_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE server_settings SET currency_old = :int_val "
                "WHERE currency = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Step 3: Drop string columns
    op.drop_column("server_settings", "units")
    op.drop_column("server_settings", "currency")

    # Step 4: Rename old columns to original names and set not null
    op.alter_column(
        "server_settings",
        "units_old",
        new_column_name="units",
        nullable=False,
    )
    op.alter_column(
        "server_settings",
        "currency_old",
        new_column_name="currency",
        nullable=False,
    )
    # Revert changes to users table
    # Step 1: Add old integer columns back
    op.add_column(
        "users",
        sa.Column(
            "gender_old",
            sa.Integer(),
            nullable=True,
            comment="User gender (1=male, 2=female, 3=unspecified)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "access_type_old",
            sa.Integer(),
            nullable=True,
            comment="User type (1=regular, 2=admin)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "first_day_of_week_old",
            sa.Integer(),
            nullable=True,
            comment="User first day of week (0=sunday, 1=monday, etc.)",
        ),
    )

    # Step 2: Migrate data from string back to integer values
    connection = op.get_bind()

    # Update gender_old based on current gender string values
    for str_val, int_val in GENDER_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users SET gender_old = :int_val " "WHERE gender = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Update access_type_old based on current access_type string values
    for str_val, int_val in ACCESS_TYPE_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users SET access_type_old = :int_val "
                "WHERE access_type = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Update first_day_of_week_old based on current first_day_of_week string values
    for str_val, int_val in WEEK_DAY_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users SET first_day_of_week_old = :int_val "
                "WHERE first_day_of_week = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Step 3: Drop string columns
    op.drop_column("users", "gender")
    op.drop_column("users", "access_type")
    op.drop_column("users", "first_day_of_week")

    # Step 4: Rename old columns to original names and set not null
    op.alter_column(
        "users",
        "gender_old",
        new_column_name="gender",
        nullable=False,
    )
    op.alter_column(
        "users",
        "access_type_old",
        new_column_name="access_type",
        nullable=False,
    )
    op.alter_column(
        "users",
        "first_day_of_week_old",
        new_column_name="first_day_of_week",
        nullable=False,
    )
    # Revert changes to users_goals table
    # Step 1: Add old integer columns back
    op.add_column(
        "users_goals",
        sa.Column(
            "activity_type_old",
            sa.Integer(),
            nullable=True,
            comment="Activity type",
        ),
    )
    op.add_column(
        "users_goals",
        sa.Column(
            "goal_type_old",
            sa.Integer(),
            nullable=True,
            comment="Goal type",
        ),
    )

    # Step 2: Migrate data from string back to integer values
    connection = op.get_bind()

    # Update activity_type_old based on current activity_type string values
    for str_val, int_val in ACTIVITY_TYPE_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_goals SET activity_type_old = :int_val "
                "WHERE activity_type = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Update goal_type_old based on current goal_type string values
    for str_val, int_val in GOAL_TYPE_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_goals SET goal_type_old = :int_val "
                "WHERE goal_type = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Step 3: Drop string columns
    op.drop_column("users_goals", "activity_type")
    op.drop_column("users_goals", "goal_type")

    # Step 4: Rename old columns to original names
    op.alter_column(
        "users_goals",
        "activity_type_old",
        new_column_name="activity_type",
        nullable=False,
    )
    op.alter_column(
        "users_goals",
        "goal_type_old",
        new_column_name="goal_type",
        nullable=False,
    )
    # Remove tileserver_api_key column from server_settings table
    op.drop_column("server_settings", "tileserver_api_key")
    # Revert comments in users_identity_providers table
    op.alter_column(
        "users_identity_providers",
        "idp_refresh_token_updated_at",
        existing_type=sa.DateTime(),
        comment="Last refresh",
        existing_comment="Last refresh token update",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "last_login",
        existing_type=sa.DateTime(),
        comment="Last time user logged in with this IdP",
        existing_comment="Last login using this IdP",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "idp_subject",
        existing_type=sa.String(length=500),
        comment="Subject/ID from the identity provider (unique per IdP)",
        existing_comment="Subject/ID from the identity provider",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
