"""v0.16.7 migration

Revision ID: 262ec21a6c15
Revises: 215d794b3041
Create Date: 2026-01-13 11:36:50.047064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "262ec21a6c15"
down_revision: Union[str, None] = "215d794b3041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mapping from old integer values to new string values
ACTIVITY_TYPE_MAP = {
    1: "run",
    2: "bike",
    3: "swim",
    4: "walk",
    5: "strength",
    6: "cardio",
}

GOAL_TYPE_MAP = {
    1: "calories",
    2: "activities",
    3: "distance",
    4: "elevation",
    5: "duration",
}

# Reverse mappings for downgrade
ACTIVITY_TYPE_REVERSE_MAP = {v: k for k, v in ACTIVITY_TYPE_MAP.items()}
GOAL_TYPE_REVERSE_MAP = {v: k for k, v in GOAL_TYPE_MAP.items()}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add tileserver_api_key column to server_settings table
    op.add_column(
        "server_settings",
        sa.Column(
            "tileserver_api_key",
            sa.String(length=512),
            nullable=True,
            comment="API key encrypted for the tile server",
        ),
    )
    # Change users_goals table
    # Step 1: Add new string columns
    op.add_column(
        "users_goals",
        sa.Column(
            "activity_type_new",
            sa.String(length=50),
            nullable=True,
            comment="Activity type (e.g., 'run', 'bike', 'swim')",
        ),
    )
    op.add_column(
        "users_goals",
        sa.Column(
            "goal_type_new",
            sa.String(length=50),
            nullable=True,
            comment="Goal type (e.g., 'calories', 'distance', 'duration')",
        ),
    )

    # Step 2: Migrate data from integer to string values
    connection = op.get_bind()

    # Update activity_type_new based on old activity_type values
    for old_val, new_val in ACTIVITY_TYPE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_goals SET activity_type_new = :new_val "
                "WHERE activity_type = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Update goal_type_new based on old goal_type values
    for old_val, new_val in GOAL_TYPE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_goals SET goal_type_new = :new_val "
                "WHERE goal_type = :old_val"
            ),
            {"new_val": new_val, "old_val": old_val},
        )

    # Step 3: Drop old integer columns
    op.drop_column("users_goals", "activity_type")
    op.drop_column("users_goals", "goal_type")

    # Step 4: Rename new columns to original names
    op.alter_column(
        "users_goals",
        "activity_type_new",
        new_column_name="activity_type",
        nullable=False,
    )
    op.alter_column(
        "users_goals",
        "goal_type_new",
        new_column_name="goal_type",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert changes to users_goals table
    # Step 1: Add old integer columns back
    op.add_column(
        "users_goals",
        sa.Column(
            "activity_type_old",
            sa.Integer(),
            nullable=True,
            comment="Activity type",
        ),
    )
    op.add_column(
        "users_goals",
        sa.Column(
            "goal_type_old",
            sa.Integer(),
            nullable=True,
            comment="Goal type",
        ),
    )

    # Step 2: Migrate data from string back to integer values
    connection = op.get_bind()

    # Update activity_type_old based on current activity_type string values
    for str_val, int_val in ACTIVITY_TYPE_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_goals SET activity_type_old = :int_val "
                "WHERE activity_type = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Update goal_type_old based on current goal_type string values
    for str_val, int_val in GOAL_TYPE_REVERSE_MAP.items():
        connection.execute(
            sa.text(
                "UPDATE users_goals SET goal_type_old = :int_val "
                "WHERE goal_type = :str_val"
            ),
            {"int_val": int_val, "str_val": str_val},
        )

    # Step 3: Drop string columns
    op.drop_column("users_goals", "activity_type")
    op.drop_column("users_goals", "goal_type")

    # Step 4: Rename old columns to original names
    op.alter_column(
        "users_goals",
        "activity_type_old",
        new_column_name="activity_type",
        nullable=False,
    )
    op.alter_column(
        "users_goals",
        "goal_type_old",
        new_column_name="goal_type",
        nullable=False,
    )
    # Remove tileserver_api_key column from server_settings table
    op.drop_column("server_settings", "tileserver_api_key")
    # ### end Alembic commands ###
