"""v0.16.7 migration

Revision ID: 262ec21a6c15
Revises: 215d794b3041
Create Date: 2026-01-13 11:36:50.047064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "262ec21a6c15"
down_revision: Union[str, None] = "215d794b3041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add tileserver_api_key column to server_settings table
    op.add_column(
        "server_settings",
        sa.Column(
            "tileserver_api_key",
            sa.String(length=512),
            nullable=True,
            comment="API key encrypted for the tile server",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove tileserver_api_key column from server_settings table
    op.drop_column("server_settings", "tileserver_api_key")
    # ### end Alembic commands ###
